import {
  Combine,
  Scissors,
  FileMinus2,
  FileOutput,
  LayoutGrid,
  Gauge,
  Wrench,
  ScanText,
  Image as ImageIcon,
  FileImage,
  FileType2,
  FileSpreadsheet,
  Presentation,
  Code2,
  Stamp,
  Hash,
  RotateCw,
  Crop,
  PenLine,
  EyeOff,
  Lock,
  Unlock,
  Sparkles,
  MessageCircleQuestion,
  Languages,
  GitCompare,
  Wand2,
  FileCode,
  FileCode2,
  Archive,
  ScanLine,
  type LucideIcon,
} from "lucide-react";

export const TOOL_ICONS: Record<string, LucideIcon> = {
  summarize: Sparkles,
  ask: MessageCircleQuestion,
  translate: Languages,
  "ai-html-to-pdf": Wand2,
  "ai-pdf-to-html": FileCode,
  compare: GitCompare,
  merge: Combine,
  split: Scissors,
  "remove-pages": FileMinus2,
  "extract-pages": FileOutput,
  organize: LayoutGrid,
  compress: Gauge,
  repair: Wrench,
  ocr: ScanText,
  "jpg-to-pdf": ImageIcon,
  "pdf-to-jpg": FileImage,
  "scan-to-pdf": ScanLine,
  "pdf-to-pdfa": Archive,
  "pdf-to-markdown": FileCode2,
  "word-to-pdf": FileType2,
  "pdf-to-word": FileType2,
  "excel-to-pdf": FileSpreadsheet,
  "pdf-to-excel": FileSpreadsheet,
  "powerpoint-to-pdf": Presentation,
  "pdf-to-powerpoint": Presentation,
  "html-to-pdf": Code2,
  watermark: Stamp,
  "page-numbers": Hash,
  rotate: RotateCw,
  crop: Crop,
  sign: PenLine,
  redact: EyeOff,
  protect: Lock,
  unlock: Unlock,
};
